// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfdjjtpseelqehfyisif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mZGpqdHBzZWVscWVoZnlpc2lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0OTUzNzYsImV4cCI6MjA2NjA3MTM3Nn0.51pVqN7lEbaa45Otr55SeB7ES2uOmk-AK1uLRjdkfhk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);